version: '3.9'

services:
    pg:
      image: postgres
      environment:
        POSTGRES_DB: table_project
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - db-data:/var/lib/postgresql/data/pgdata
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready" ]
        interval: 5s
        timeout: 3s
        retries: 7

    pgadmin:
      image: "dpage/pgadmin4"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: passwd!
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin
      ports:
        - "5003:80"

volumes:
  db-data:
  pgadmin:
