version: '3.9'
services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: table_homework_6
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 7
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: passwd!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  app: &app-config
    build:
      dockerfile: docker-build/app/Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
    ports:
      - "1080:80"
    depends_on:
      pg:
        condition: service_healthy
  app-dev:
    <<: *app-config
    build:
      dockerfile: docker-build/app-dev/Dockerfile
    environment:
      CONFIG_NAME: DevelopmentConfig
    ports:
      - "1081:5000"
    volumes:
      - ./app:/app

volumes:
  db-data:
  pgadmin:
