version: '3.7'
services:
  pg:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: table_homework_6
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
  flask:
    # Собираем приложение по Dockerfile
    build: ./flask-app
    # Имя для создаваемого контейнера
    container_name: flask
    # Запуск приложения
#    command: gunicorn wsgi:app -b 0.0.0.0:5555 --reload
    # Создание переменных окружения в контейнере
#    environment:
    # Перезапускаем сервис
    restart: always
    # Прокладывам путь для файлов. Все файлы, которые хранятся в
    # директории ./flask-app, появятся в директории контейнера /flask-app
    volumes:
      - /usr/src/flask-app
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "5555:5555"
    depends_on:
      - pg


volumes:
   db-data:
