version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: table_homework_4
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata

volumes:
  db-data:


# to use the database run in the terminal - docker compose up -d pg
